config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  get 'products/index'
  get 'products/carts'
  resources :products_cart
  devise_for :users, controllers: {
      confirmations: 'users/confirmations',
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations',
      unlocks: 'users/unlocks',
    }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :image
  has_many :product_carts, dependent: :destroy
end

app/models/product_cart.rb
class ProductCart < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable
  has_many :product_carts
  has_many :products, through: :product_carts, source: :product
  has_many :cart_products, -> { where(product_carts: { in_cart: true }) }, through: :product_carts, source: :product
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_cart_controller.rb
class ProductsCartController < ApplicationController
  def create
    ProductCart.create(user_id: params[:user], product_id: params[:product], in_cart: true )
    redirect_to controller: 'products', action: 'carts'
  end

  def destroy
    @product = ProductCart.where(user_id: current_user.id, product_id: params[:id], in_cart: true ).first
    if @product
      @product.destroy
    end
    redirect_to controller: 'products', action: 'carts'
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  def index
    @products = Product.all
  end

  def carts
    @products = current_user.cart_products
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_cart_helper.rb
module ProductsCartHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ESystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/carts.html.erb
<div class="btn-group" role="group" aria-label="Basic example">
  <%= link_to 'All products', root_path, class: 'btn btn-secondary' %>
  <%= link_to 'Cart Products', products_carts_path, class: 'btn btn-secondary' %>
</div>
<%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-secondary' do %>
  Log Out
  <i class="fa fa-fw fa-sign-out-alt text-danger ml-1"></i>
<% end %>

<h1 class="text-center">Carts Products</h1>
<div class="row row-deck" style="margin-top: 50px;">
  <% @products.each do |product| %>
    <div class="mt-3 mx-2 card" style="width: 18rem;">
      <% if product.image.attached? %>
        <%= image_tag product.image, class: 'card-img-top', size: "200x200", alt: 'Card image cap' %>
      <% end %>
      <div class="card-body">
        <h5 class="card-title"><%= "Name : #{product.name}" %></h5>
        <p class="card-text"><%= "Price : #{product.price}" %></p>
        <p class="card-text"><%= "Quantity : #{product.quantity}" %></p>
         <%= link_to products_cart_path(product), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-secondary' do %>
          Remove from cart
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/products/index.html.erb
<div class="btn-group" role="group" aria-label="Basic example">
  <%= link_to 'All products', root_path, class: 'btn btn-secondary' %>
  <%= link_to 'Cart Products', products_carts_path, class: 'btn btn-secondary' %>
</div>
<%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-secondary' do %>
  Log Out
  <i class="fa fa-fw fa-sign-out-alt text-danger ml-1"></i>
<% end %>

<h1 class="text-center">All Products</h1>
<div class="row row-deck" style="margin-top: 50px;">
  <% @products.each do |product| %>
    <div class="mt-3 mx-2 card" style="width: 18rem;">
      <% if product.image.attached? %>
        <%= image_tag product.image, class: 'card-img-top', size: "200x200", alt: 'Card image cap' %>
      <% end %>
      <div class="card-body">
        <h5 class="card-title"><%= "Name : #{product.name}" %></h5>
        <p class="card-text"><%= "Price : #{product.price}" %></p>
        <p class="card-text"><%= "Quantity : #{product.quantity}" %></p>
        <%= link_to products_cart_index_path(product: product.id, user: current_user.id), method: :post, class: 'btn btn-secondary' do %>
          add to cart
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>